custom:
  value: nwfff11
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/starcloud?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: redispwd
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml, application/xml, application/json
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  sentinel:
    enabled: true
